/*
 * Microsoft Bot Connector API - v3.0
 * The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    Â© 2016 Microsoft
 *
 * OpenAPI spec version: v3
 * Contact: botframework@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AttachmentInfo;
import io.swagger.client.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AttachmentsApi
 */
@Ignore
public class AttachmentsApiTest {

    private final AttachmentsApi api = new AttachmentsApi();

    
    /**
     * GetAttachment
     *
     * Get the named view as binary content
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void attachmentsGetAttachmentTest() throws ApiException {
        String attachmentId = null;
        String viewId = null;
        byte[] response = api.attachmentsGetAttachment(attachmentId, viewId);

        // TODO: test validations
    }
    
    /**
     * GetAttachmentInfo
     *
     * Get AttachmentInfo structure describing the attachment views
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void attachmentsGetAttachmentInfoTest() throws ApiException {
        String attachmentId = null;
        AttachmentInfo response = api.attachmentsGetAttachmentInfo(attachmentId);

        // TODO: test validations
    }
    
}
